name: facebook_web_sdk
description: Facebook js sdk wrap for dart
version: 0.0.9
homepage: https://github.com/leftyio/facebook_web_sdk
author: Kevin Segaud <kevin.segaud@gmail.com>

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  js: ^0.6.1+1
  dart_browser_loader: ^0.0.5